### PR TITLE
Override sequence

### PR DESCRIPTION
**Pull request by jtonk**
- provides override function without additional variable
- combined arm HOME and arm AWAY into one function
- changed arm/disarm service to Alarmo instead of the native arm/disarm service

### CODE REVIEW

**Review by ImSorryButWho — CHANGES_REQUESTED** [review]
Sorry, just got around to looking at this.  On line 156, you've hardcoded the name `alarm_control_panel.alarmo`.  That should be `!input alarm`.

**Comment by jtonk** [comment]
corrected. by the way do you have a way to update the firmware? I have on keypad in 1.18 and one in 1.16. The 1.16 device doesn't hold the colored arm status lights.

**Comment by ImSorryButWho** [comment]
Thanks, I'll give this a test in the next few days.

As far as firmware updates, I'm not aware of any publicly-available updates for the keypad.  It's possible you could use the SILabs tools to extract the firmware from one to apply to the other, but I'm not sure whether that's actually feasible.  Maybe I'll pick up another keypad and try it for fun.

**Comment by ImSorryButWho** [comment]
Got a chance to test this out - looks like it works great.  Thanks so much for your help with this!

**Comment by jtonk** [comment]
my pleasure!

**Pull request merged**
